#!/bin/bash
mv run.inp MINP
dmrcc > run.log
rm fort.* CCDENSITIES COORD.xyz DAO DENSITY.SCF EXIT FOCK iface KEYWD MOCOEF MOLDEN MOLDEN.perm MOMENT mrcc_job.dat OCCUP OEINT PLUSCORE.55 PRINT SCFDENSITIES* SCHOL SROOT SYMTRA TEDAT TEINT VARS
mv MINP run.inp
